"""
Django settings for hivapp project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from os import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'https://39927783.qcloud.la','118.89.146.122']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hiv',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hivapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hivapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# weixinapp addtion
<<<<<<< HEAD
WXAPP_ID = ''
=======
WXAPP_ID = 'wxc066d762e4dd7357'
>>>>>>> origin/master
WXAPP_SECRET = ''
WXAPP_TOKE = ''
GRANT_TYPE = 'authorization_code'


# JWT issues
ISS = environ.get('ISS', 'iss')
AUDIENCE = environ.get('AUDIENCE', 'audience')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ofctkgm9(!yan_^g%h6)q@9x_s^o+&guc8v(uo27ppkta-d4bf'

# database configuration
MONGO_HOST = "localhost"  # 主机IP
MONGO_PORT = 27017  # 端口号
MONGO_DB = "HIVAPP"# db名
MONGO_COLL = "userinfo" # collection名
MONGO_COLL1 = "orderinfo" # collection名
MONGO_COLL2 = "sessioninfo" # collection名


# error_codes
ERROR_CODES = {
    'wxapp_not_registered': ('The wxapp not registered', '微信没有注册'),
    'invalid_wxapp_code': ('Invalid wxapp code', '无效的code'),
    'invalid_token': ('Invalid token', '无效的rd3'),
    'reregister':  ('Reregister', '请重新登录'),
    'wxapp_already_registered': ('The weixin app already registered', '账号已被注册'),
    'request_lost': ('Request Lost ', '请求失效'),
    'request_overdue': ('Rquest Overdue', '请求过期'),
    'register_fail': ('Register Fail', '注册失败' ),
}
